### PR TITLE
SVT November Meetup

### PR DESCRIPTION
**Pull request by Ephem**
# Description

This is an event that will take place at SVT the 15th of November. There are still one or two spots open for lightning talks.

This is also the first PR with a meetup, based on unfinished scaffolding. The idea is that the host themselves do these PRs in the future, but since it's still in alpha, we decided to start out on this one ourselves.

### CODE REVIEW

**Comment by Bogdan-Lyashenko** [comment]
@Ephem hey, can you please fix my name spelling? Correct form is 'Bohdan Liashenko'. Thanks ;)

**Comment by Ephem** [comment]
I’m so sorry! I was sure I double-checked the spelling of all the names, but apparently should have tripple-checked.. :)

Will update PR and Meetup.com ASAP (this afternoon).

**Comment by Ephem** [comment]
I think I went by your GitHub-handle instead of checking your bio, fixed here and on Meetup.com now!

**Comment by Bogdan-Lyashenko** [comment]
@Ephem thanks, no worries 😃

**Pull request merged**
